### PR TITLE
Image Widget infrastructure and settings page

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees This is just the core files and the settings page. Please review. Thx.

**Comment by donnapep** [comment]
@stulees Good point. Looks like I'll have to validate on the save then.

**Comment by donnapep** [comment]
@stulees Also forgot to mention that I updated Angular to 1.3.10 and didn't encounter any issues.

**Comment by donnapep** [comment]
@stulees Please review again. Also, I forgot to commit the `dist` folder so that's in here now too. Thx.

**Comment by stulees** [comment]
@donnapep Few things:
- I don't think this `$watch` is necessary - http://goo.gl/pnKGGH . You're already setting the default value of `url` here - http://goo.gl/oObjV0 . URL Field will be invalid due to this and will show its invalid controls. Also, from there on if the value is ever `""`, it will be invalid. 
- `ng-blur` should be removed - http://goo.gl/GgBz5n
- I don't follow why this block of code is necessary - http://goo.gl/VPshZE Can you clarify?
- Now that `blur` isn't necessary, I think URL Field should be updated to remove this previous update of `$emit` the `urlFieldBlur` event.

**Comment by donnapep** [comment]
@stulees Please see below. My bullet points match up with yours:

- This is similar to the piece of code you have in video for ensuring that the Save button is disabled when URL is empty. However, I don't think I need to be setting `imageUrl` here since it's set in the other watcher. I've taken that part out.
- I've removed `ng-blur`.
- Some of the settings are only visible if the URL is valid. Also, if the URL isn't valid, the Save button shouldn't be enabled.
- I don't think it hurts to leave it in as I could see it being useful in the future, and would save having to add it back in at that time.

Thx.

**Comment by stulees** [comment]
@donnapep Okay, thanks for clarifying. Regarding the 3rd point, just a suggestion, but alternatively you could do away with maintaining a scope variable and could base the conditional value of `ng-show` in your settings on `settingsForm.urlField.$error.valid`.
Registering for `ng-blur` on the `input` field of URL Field component and doing an `$emit` of an event seems like performance overhead considering we don't need it. Okay to leave for now, but if it still seems like it's not being used in the future, lets remove. Thanks :+1:

**Comment by donnapep** [comment]
@stulees I can't actually do that because on that first load when the URL is empty `settingsForm.urlField.$error.valid` will be `true`.

What about having a configurable setting in the URL component for specifying whether an empty URL should be treated as valid or invalid? I think that would eliminate a lot of the problems I currently have with it. If I could set it so that an empty field was treated as being invalid, then I could use
`settingsForm.urlField.$error.valid` for showing / hiding, and I think that would also eliminate that initial watcher that I have to use in order to make the entire form invalid so that Save is disabled. Does that make sense?

I'm also still not done with this PR just yet. I think I need to actually validate the file extension in addition to checking it's a valid image file. Reason being that otherwise those settings that are only supposed to show after a valid image URL has been entered, will currently show up right after the URL component deems that it's a valid URL, which is too soon. I'll be adding this to the image validator service.

Finally, re: `ng-blur`, very little code was added to implement this, so I'm not at all concerned about any additional overhead. Don't forget that just because we're not using this functionality, doesn't mean someone else isn't using our component and could benefit from it. Having said that, you own that component, so do what you like. I get that it's your baby. :)

**Comment by donnapep** [comment]
@stulees When a URL is valid as specified by the URL field component, a second check is run to validate the file extension. Once a valid file extension is entered, the hidden settings will be shown. The final and ultimate check is when clicking Save. At that point the URL gets a final check to ensure that it's actually an image. Please review. Thx.

**Comment by stulees** [comment]
@donnapep Okay, this is interesting, I've discovered an unexpected behaviour happening when URL Field is used in the context of a widget settings that I hadn't noticed before. It's what's been adding to confusion on my side. 

To explain, try testing URL Field in the browser from widget-settings-ui-components via the use of our `e2e:server` task. You'll notice that the invalid controls don't show and the component is deemed valid. This is because of no default value. Now try adding `url:""` to `additionalParams` in the test page. Test it again and you'll see the invalid controls show and the component is deemed invalid. This is the behaviour I expect and have intended it to work. However, I'm noticing now that having the `url:""` in `additionalParams` doesn't make a difference in the way we build our widget settings and I'm not sure why. 

Regarding your updates, apart from one comment, LG :+1:

**Comment by donnapep** [comment]
@stulees OK, does that mean there's a bug that needs to be fixed?

**Comment by stulees** [comment]
@donnapep I guess so, but it doesn't seem like it's an issue with url field itself as it works as expected (and how you also want it) when you test it in widget-settings-ui-components. I'll need to investigate further. Thanks

**Pull request merged**
