### PR TITLE
Hiding visibility of single image when widget paused [stage-2]

### PR DESCRIPTION
**Pull request by stulees**
- To ensure an animated gif is not taxing the browser unnecessarily, hiding visibility of image when viewer has paused Widget
- Added integration tests

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review, thanks

**Comment by rodrigopavezi** [comment]
@stulees looks good 👍 cheers

**Comment by stulees** [comment]
@donnapep Please review last commit, thanks

**Comment by donnapep** [comment]
👍

**Comment by stulees** [comment]
@rodrigopavezi This current state of the code has the removal of a cache buster still applied for refreshing 3rd party single image. Are we deploying with that or should we be adding that back?

**Pull request merged**
