### PR TITLE
Handling storage api error and displaying message [stage-2]

### PR DESCRIPTION
**Pull request by stulees**
- Using latest `rise-storage` and handling "rise-storage-api-error" for storage file and folder instances
- Added integration tests

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review. I can't see a way to be able to force a storage api error to validate this with a presentation. Any ideas? Thanks

**Comment by donnapep** [comment]
@stulees Not sure. You could check with Ezequiel or Rodrigo when he's back tomorrow. I think he knows how to reproduce. :+1:

**Comment by stulees** [comment]
@donnapep Spoke with @fjvallarino and the only way we can force an API error is with an invalid company, but we cover that already with our subscription logic. Otherwise error(s) only happen when a GCS call fails (Google's side). We can't actually force that.

**Comment by rodrigopavezi** [comment]
@stulees @donnapep that is right, I don't think we can reproduce the error. Looks good :+1: cheers

**Pull request merged**
