### PR TITLE
Merge image folder settings [stage-1]

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Test Presentation is here - http://rva.risevision.com/#/PRESENTATION_MANAGE/id=74843572-e62b-45dd-a279-2ce3e59b85a0?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013. Thx.

**Comment by stulees** [comment]
@donnapep I noticed you removed Background setting entirely, I didn't realize we weren't going to support it moving forward. Can you confirm I should remove it in the widget implementation?

**Comment by donnapep** [comment]
@stulees That's correct. It's been removed as per the UX. I'm fairly certain @mmeiers didn't think it was a useful setting to have since it get be set at the Placeholder level.

Also, I just added another commit to remove the "Resume Playing from Last Position" setting since it wasn't part of original Image Folder. As there's a separate card in the backlog for it, I've just commented everything out for now.

Thx.

**Comment by stulees** [comment]
@donnapep Looks good :+1: I can take merging these two branches as I need to update the widget implementation to ignore the background setting. Okay with you?

**Comment by donnapep** [comment]
@stulees Yup, sounds good. Thx.

**Pull request closed without merging**
