### PR TITLE
Upgrade widget-common repo

### PR DESCRIPTION
**Pull request by donnapep**
This should go after PR #87.

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by stulees** [comment]
@donnapep https://github.com/Rise-Vision/widget-image/pull/87 is approved but not merged because we can't validate on uptime wall yet. Is this PR a branch off that PR's branch?

**Comment by donnapep** [comment]
@stulees Ah, no it's not. I guess we should hold on upgrading `widget-common` in Image and Video Widgets until after that one gets deployed, yes?

**Comment by stulees** [comment]
@donnapep Yeah the work I'm doing for handling 202 and done call is going to be a further commit to that branch in PR #87 so that it can all be validated together. I can review these PRs but they should be blocked from merging until #87 gets merged.

**Comment by donnapep** [comment]
@stulees OK, that's fine. This can be rebased afterwards.

**Comment by stulees** [comment]
@donnapep 👍

**Comment by donnapep** [comment]
@stulees This PR has also been rebased against your other PR. Thx.

**Comment by stulees** [comment]
@rodrigopavezi Please review last commit, thanks

**Comment by rodrigopavezi** [comment]
@stulees looks good 👍  cheers

**Pull request merged**
