### PR TITLE
Show / hide image for .gifs only

### LINKED ISSUE #102: Random white flashes in between playlist items.
**How to recreate**
Assign multiple Image Widgets w/images to a placeholder in two presentations. (Test presentations [here](https://apps.risevision.com/editor/workspace/28e2500a-ed80-4ac7-8434-dd40131ff9f9/?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55) and [here](https://apps.risevision.com/editor/workspace/f703276f-217b-404d-830d-f596767955c3/?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55).)
Set the transition of those placeholders to "None".
Assign both presentations to a schedule.
Assign schedule to a display.

**What happens**
The presentation will play through the placeholder items, occasionally, the screen will flash white in between the placeholder items.

**What should happen**
1) The presentation should
 - Play image after image with no white flash

2) The schedule should
 - Play scheduled presentations no white flash

**Notes**
Video [here](http://www.screencast.com/t/NvlaMmBJ)
Schedule [here](https://apps.risevision.com/schedules/details/600c0db4-bfef-4ff7-847f-eaa2f6d74454?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55)
I have attempted to recreate with calendar/video/web page widget and I am not able to recreate. 

**Operating System:** 64-bit Microsoft Windows 10 Pro
**Player Version:** RisePlayerElectron 2016.10.13.00.42
**Viewer Version:** 2-00-201610041830
**Browser Version:** Chrome 52.0.2743.82

### PR DESCRIPTION
**Pull request by donnapep**
Fixes #102.

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by stulees** [comment]
@donnapep 👍

**Comment by stulees** [comment]
@donnapep Whoops, take that back. I think the dist/ files are missing

**Comment by donnapep** [comment]
@stulees Oops, fixed. Thx.

**Comment by stulees** [comment]
@donnapep 👍

**Pull request merged**
