### PR TITLE
Upgrade rise-storage

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by rodrigopavezi** [comment]
@donnapep looks good. :+1:  cheers

**Comment by stulees** [comment]
@donnapep :+1:

**Comment by rodrigopavezi** [comment]
@donnapep I tested it here http://rva.risevision.com/#/PRESENTATION_MANAGE/id=86d0f2e5-4f32-4a34-a5f6-2263e5c30b75?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013 and there is an issue with the storage selector. I reckon it could be because you are not adding a resolution on bower for it. cheers

**Comment by donnapep** [comment]
@rodrigopavezi That Presentation is using Image Folder Widget. This PR is for Image Widget. Thx.

**Comment by rodrigopavezi** [comment]
@donnapep sorry, my bad. looks good.

**Comment by donnapep** [comment]
@rodrigopavezi Great, thanks for validating.

**Comment by mmeiers** [comment]
@donnapep can this be merged?

**Comment by donnapep** [comment]
@alanclayton Unfortunately no. It's too late on a Friday to deploy changes.

**Comment by donnapep** [comment]
@mmeiers Oops. Please see the above comment. Thx.

**Pull request merged**
