### PR TITLE
Deploying staged minified and unminified versions [stage-2]

### PR DESCRIPTION
**Pull request by stulees**
- Deploying a stage "-dev" bucket with unminified code as well as a stage bucket with production minified code

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review. The idea is a test `stage-_-dev` bucket will be created first with unminified code and then a production `stage-_` bucket gets created with minified code. I thought this would happen within this PR but I guess the circle file needs to be merged to master first?

**Comment by donnapep** [comment]
@stulees Just so I understand, will this mean we will no longer have a `widget-image-test` bucket for example, and instead will have a `widget-image-dev` bucket? Where will our development version with uncompressed code reside? Thx.

**Comment by stulees** [comment]
@donnapep No, all of this is still within the `widget-image-test` bucket. Inside that bucket, would be `stage-_` and `stage-_-dev`.

**Comment by donnapep** [comment]
@stulees OK, the word "bucket" was throwing me off. That makes sense. :+1:

**Comment by stulees** [comment]
@donnapep Ok thanks.
@rodrigopavezi Does this look good to you? Particularly this line - https://github.com/Rise-Vision/widget-image/blob/a7c6e2c4baced86f9566f438d20f7e4566317416/circle.yml#L44 . I'm not sure if it should be `STAGE_ENV=STAGE_ENV + '-dev'; ` instead.

**Comment by rodrigopavezi** [comment]
@stulees I think you have to do something like that `STAGE_ENV="$STAGE_ENV-dev"` cheers

**Comment by rodrigopavezi** [comment]
@stulees looks good :+1: cheers

**Comment by stulees** [comment]
@rodrigopavezi thanks!

**Pull request merged**
