### PR TITLE
Add support for logging

### PR DESCRIPTION
**Pull request by donnapep**
The way in which errors are logged for Image Widget is different from how they are logged for Video. To facilitate writing queries, errors are now logged with `error` as the `event`, and the particular type of error (e.g. `storage file not found`) is logged in `event_details`.

### CODE REVIEW

**Comment by donnapep** [comment]
@rodrigopavezi @stulees Please review. Thx.

**Comment by stulees** [comment]
@donnapep There's some repetitive code in `image.js`:

```
fileUrl = params.url + separator + "cb=" + new Date().getTime();
img.style.backgroundImage = "url(" + fileUrl + ")";
```

Could this be put into a function so its reused? Otherwise, :+1:

**Comment by donnapep** [comment]
@stulees Please take another gander. Thx.

**Comment by stulees** [comment]
@donnapep :+1:

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review latest commit. Also, @rodrigopavezi, I've not included logging a status code for a cache or storage error. The `event_details` field is now taken up by the type of error, so if we wanted to capture this info we would need to add another field. Given that Video Widget always returns a status of 0 for those error types, I'm not sure it's worth it.

**Comment by rodrigopavezi** [comment]
@donnapep good point. I think it is woth to have this detail. The only case it will always return status of 0 is when using native rise cache but that should be fixed. For the other cases we will be able to see why the request failed. @stulees what do you think? cheers

**Comment by stulees** [comment]
@donnapep @rodrigopavezi I agree, I think it's worth adding a new field. When running on CAP we get accurate status codes. Hopefully Rise Cache on native will get fixed at some point soon and we get accurate status codes then too. 

I suppose we are going to need to go back at some point and get Video in line with how Image does the logs, or do you think it's best to leave it?

**Comment by donnapep** [comment]
@rodrigopavezi @stulees Please review latest commit. Re: updating video to do the same. I actually don't think we should worry about it because it would only complicate the BQ queries for video further, and we can't go back and update existing data in BQ. Thx.

**Comment by stulees** [comment]
@donnapep :+1:

**Pull request merged**
