### PR TITLE
Change when configuration event is logged [stage-2]

### PR DESCRIPTION
**Pull request by stulees**
- Moved log of configuration event to `play()` function and ensuring only logged once
- test coverage revised

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review, thanks

**Comment by donnapep** [comment]
@stulees Not sure if you've encountered the same thing, but when I put Video on a Player, it didn't actually log the configuration event. It looks like a timing issue in the logger that I'm going to look into how to fix. Thx.

**Comment by stulees** [comment]
@donnapep Yes I can confirm the same for Image, the configuration event doesn't get logged. I'll wait to hear from you on the fix to our Logger module, thanks.

**Comment by donnapep** [comment]
@stulees Since I'm off tomorrow, I expect someone else will be picking this up. Here's the summary:

The problem is when waiting for the company and display IDs to be returned by Viewer. First the configuration event kicks off this request. Viewer has not yet returned the IDs when the play event comes along, so it kicks off another request, and **the `json` object for the configuration event gets overwritten by the properties of the `play` event**. So now when the RPC call finally returns, the `json` object has incorrect values.

I've tried passing the `json` object to the RPC call, but Viewer does not return it with its response. So I gave up on that. The solution may be to only make one RPC call for the IDs and then queue up the logging events until the IDs are returned. Or perhaps there's some simpler solution. Regardless, a fresh pair of eyes on this will be good.

Thx.

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review last two commits, thanks

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
