### PR TITLE
Fix/Reduce excessive widget logging into BQ

### PR DESCRIPTION
**Pull request by jungeunyoon**
Reduces logging to BQ by 95% by removing play and done events.

This won't be merged until all BQ queries are adjusted to use `Configure` event (also backwards compatible with `play` event.)

### CODE REVIEW

**Comment by jungeunyoon** [comment]
[Reduce excessive widget logging into BQ [3]](https://trello.com/c/Ea5JQ8Jq/4840-reduce-excessive-widget-logging-into-bq-3)

**Comment by stulees** [comment]
@jungeunyoon @rodrigopavezi There is PR #142 that is very large and will soon be merged. It involves a lot of code changes and refactoring and it bumps the version of the Widget so we can deploy to a new bucket so we temporarily don't impact existing presentations. It would be best if your PR here **doesn't** get merged until after 142. I expect to merge 142 early next week or potentially sooner. Does this work for you?

**Comment by sheadarlison** [comment]
@stulees we paused work on this till @jungeunyoon is back, she's out sick and won't be back till Monday at the earliest so I don't think there's an issue.

**Comment by stulees** [comment]
@sheadarlison Okay thanks!

**Pull request merged**
