### PR TITLE
Widget implementation of merging Folder [stage-2]

### PR DESCRIPTION
**Pull request by stulees**

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review, thanks. (sorry for the size of this PR)

**Comment by rodrigopavezi** [comment]
@stulees code looks good. I couldn't test the image folder though due to the url validation. How are you checking that? cheers

**Comment by stulees** [comment]
@rodrigopavezi Going to try and set up something to validate that now, will let you know, thanks.

**Comment by stulees** [comment]
@rodrigopavezi I've tried to hardcode the additionalParams values in the HTML tab of the presentation but it doesn't seem to persist and is causing problems with managing the presentation. I don't think the Folder logic of this PR can be validated until the merge of the Settings are complete. I think we're actually going to have to merge the two branches to do so. @donnapep FYI

**Comment by stulees** [comment]
@rodrigopavezi I forgot to mention that I have validated that it works locally when I've been testing using our Widget Preview app and some hardcoded changes.

**Comment by stulees** [comment]
@rodrigopavezi @donnapep Disregard my last comments, I've hardcoded the expected `additionalParams` values in a presentation that will be used once we merge Settings. You can validate folder logic works as well as storage file and non-storage.

http://preview.risevision.com/Viewer.html?type=schedule&id=a7a21d9d-b995-4240-b748-707cf6df6fb6

Here is the presentation, but don't try and configure the settings, they have values hardcoded in the HTML.  
http://rva.risevision.com/#/PRESENTATION_MANAGE/id=e71dfa97-b5bd-4062-a151-5529a858e886?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013

**Comment by rodrigopavezi** [comment]
@stulees looks good!! :+1: cheers

**Comment by stulees** [comment]
@donnapep @rodrigopavezi FYI, I've closed PR #27 and merged/rebased the commits from that PR into this PR so we can deploy together. Please do a quick review, thanks.

**Comment by donnapep** [comment]
:+1: Also reviewed the background color removal commit.

**Comment by stulees** [comment]
@donnapep thanks!

**Comment by rodrigopavezi** [comment]
@stulees looks good :+1: cheers

**Comment by stulees** [comment]
@donnapep Last commit fixes the scale to fit problem with folder, thanks.

**Comment by donnapep** [comment]
:+1:

**Comment by donnapep** [comment]
@stulees Please review latest commit. Thx.

**Comment by stulees** [comment]
@donnapep :+1:

**Pull request merged**
