### PR TITLE
Update Storage Iframe

### PR DESCRIPTION
**Pull request by ezequielc**
[stage-4]

@stulees Please review. Thanks!

### CODE REVIEW

**Comment by ezequielc** [comment]
Presentation with a widget: 

http://rva.risevision.com/#/PRESENTATION_MANAGE/id=620bc22e-a2be-40a6-885b-2b0c220eef75?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013

**Comment by stulees** [comment]
@ezequielc You'll need to update the config files `dev.js` and `test.js` to change their `STORAGE_MODAL` values to the new test version.

https://github.com/Rise-Vision/widget-image/blob/master/src/config/dev.js#L8
https://github.com/Rise-Vision/widget-image/blob/master/src/config/test.js

Also, we shouldn't merge/deploy any changes until @alanclayton has validated. You might need to create a card in Content in our Validation column and flag @alanclayton , or ask him what he'd prefer. Thanks

**Comment by ezequielc** [comment]
Thanks @stulees I updated the config files. I will talk with @alanclayton about deployment.  Thanks again!

**Comment by ezequielc** [comment]
@stulees @alanclayton Are we good to merge this? Thanks!

**Comment by stulees** [comment]
@ezequielc :+1: Looks good

**Comment by alanclayton** [comment]
@ezequielc :+1:

**Pull request merged**
