### PR TITLE
Dynamically adding rise-storage based on Rise Cache version [stage-2]

### PR DESCRIPTION
**Pull request by stulees**
- `main.js` checks RC version and dynamically adds all rise-storage dependencies and configures which version of rise-storage is used

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review, thanks

**Comment by rodrigopavezi** [comment]
@stulees actually, I had an idea. what if we create an integration test that have a sinon mock fakeServer to respond like rise cache v2 is online then we will check the DOM to see if the import has v2 in it? cheers

**Comment by stulees** [comment]
@rodrigopavezi Hm, might be possible. I'll have to try that out.

**Comment by rodrigopavezi** [comment]
@stulees I think it is worth it. cheers

**Comment by stulees** [comment]
@rodrigopavezi Please review last commit, thanks. I will add these same tests to the Video Widget.

**Comment by rodrigopavezi** [comment]
@stulees awesome!!! 👍 cheers

**Comment by stulees** [comment]
@donnapep Please review last commit, thanks

**Comment by donnapep** [comment]
👍

**Comment by stulees** [comment]
@donnapep Please review last commit, thanks

**Comment by donnapep** [comment]
👍

**Comment by stulees** [comment]
@donnapep Please review last commit, thanks

**Comment by donnapep** [comment]
👍

**Comment by stulees** [comment]
@donnapep Please review last commit (again), thanks

**Comment by donnapep** [comment]
👍

**Comment by donnapep** [comment]
@stulees I take back my approval. On [this line](https://github.com/Rise-Vision/widget-image/pull/87/commits/b55e4c5dba4d586bffc57346806bb2ac362a53c1#diff-de19658a8a62459cee4fa3588cf9466eR164), `image` isn't actually an array.

Is it possible to add some test coverage to check the visibility of an image if a file is unavailable?

**Comment by stulees** [comment]
@donnapep Please review last commit, includes test coverage. Thanks

**Comment by donnapep** [comment]
👍

**Comment by stulees** [comment]
@rodrigopavezi Please review last commit, thanks.

**Comment by rodrigopavezi** [comment]
@stulees looks good 👍  cheers

**Pull request merged**
